### config ###

# See https://www.mkdocs.org/user-guide/configuration/.

INHERIT: !ENV MKDOCS_BASE_CONFIG

### navigation ###

nav:
  - Guia da pessoa usuária:
      - Começando: user-guide/getting-started.md
      - Uso da linha de comando: user-guide/command-line-usage.md
      - user-guide/rule-levels.md
      - user-guide/baseline.md
      - user-guide/discovering-symbols.md
      - user-guide/output-format.md
      - user-guide/ignoring-errors.md
      - user-guide/stub-files.md
      - user-guide/troubleshooting-types.md
      - user-guide/result-cache.md
      - user-guide/extension-library.md
      - user-guide/backward-compatibility-promise.md
  - config-reference.md
  - Writing PHP Code:
      - writing-php-code/phpdocs-basics.md
      - writing-php-code/phpdoc-types.md
      - writing-php-code/solving-undefined-variables.md
      - writing-php-code/narrowing-types.md
  - Developing Extensions:
      - developing-extensions/extension-types.md
      - developing-extensions/core-concepts.md
      - developing-extensions/abstract-syntax-tree.md
      - developing-extensions/scope.md
      - developing-extensions/type-system.md
      - developing-extensions/trinary-logic.md
      - developing-extensions/reflection.md
      - developing-extensions/dependency-injection-configuration.md
      - developing-extensions/rules.md
      - developing-extensions/collectors.md
      - developing-extensions/error-formatters.md
      - developing-extensions/class-reflection-extensions.md
      - developing-extensions/dynamic-return-type-extensions.md
      - developing-extensions/dynamic-throw-type-extensions.md
      - developing-extensions/type-specifying-extensions.md
      - developing-extensions/custom-phpdoc-types.md
      - developing-extensions/always-read-written-properties.md
      - developing-extensions/always-used-class-constants.md
      - developing-extensions/always-used-methods.md
      - developing-extensions/allowed-subtypes.md
      - developing-extensions/testing.md
      - developing-extensions/result-cache-meta-extensions.md
      - developing-extensions/backward-compatibility-promise.md
      - API Reference: "https://apiref.phpstan.org/"
